development: &development
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: biohacking_development
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres
  host: localhost

test: &test
  <<: *development
  database: biohacking_test

production: &production
  <<: *development
  database: biohacking_production